trigger:
  - main

pool:
  name: 'UbuntuSunucuPool'

steps:
- script: |
    echo "1. ADIM: Yeni kodlar sunucu klasörüne aktarılıyor..."
    rsync -av --exclude='.git' --exclude='.env' $(Build.SourcesDirectory)/ ~/SigortaWebSitesi/
  displayName: 'Kodları Canlı Klasöre Senkronize Et'

- script: |
    echo "2. ADIM: Docker konteynerları arka planda güncelleniyor..."
    cd ~/SigortaWebSitesi
    docker compose up -d --build
  displayName: 'Docker Konteynerlarını Yeniden İnşa Et (Zero-Downtime)'