services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      # Azure SSL gerektirir, bunu eklemek hayat kurtarır
      POSTGRES_SSLMODE: require 
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      # Next.js build aşamasında API adresini bilmek ister
      args:
        - NEXT_PUBLIC_API_URL=http://20.238.6.4:8000/api
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://20.238.6.4:8000/api
    depends_on:
      - backend